### ISSUE TITLE
The Scrollbar won't appear, if the Container exceeds the map (within IFrame)

### ISSUE THREAD

**Issue by Koni93** [davicustodio/Leaflet.StyledLayerControl#7] opened 2015-06-22 16:58 UTC
As mentioned above, the vertical scrollbar wont appear if the container exceeds the map. 
The map is located on a website inside an IFrame. 
I have changed the container_maxHeight to an appropriate value in (given options) and directly the overflow-y and height attributes in the styledLayerControl.css in every possible way. Both havent worked properly.
If I use overflow-y: auto;  the scrollbar appears right at the beginning, but is unusable (cant really scroll, its just one long bar). If the bar is hidden i cant scroll as well (of course ;) ).
I dont want to change the height:auto. That way its kind of dynamic.

**Comment by davicustodio** [comment] 2015-06-22 17:26
Koni93, I tried in various ways to reproduce the problem of the scroll bar disappear when the main container passes the map size.
I tested the Chrome and Firefox, and could not make the scroll bar disappears.
Have you ever tested your application by turning off an IFrame?
I'm no expert in CSS and I can not tell you if any changes should happen because of the IFrame, but it's worth testing.
You could spend a link so that I can try? If you do not feel comfortable in posting here, can be offline to my email.

**Comment by davicustodio** [comment] 2015-06-24 17:32
Koni, thank you for taking your webgis so I could play your situation.
I managed to find the problem. When you specify a value for container_maxHeight, type "400px", the plugin in _on_resize_window event had just adding another px value, staying as "400pxpx". It made the StyledLayerControl the container does not resize to the current size of the map.
The Fix is in 9660ef9f5d6be927185a48feae3e0b16dbe3d461.
The master is updated too.

Thanks

**Comment by Koni93** [comment] 2015-06-24 18:24
Changed/updated everything and worked for me. 
Is it intended to use 'container_maxHeight : "450" ' as a number without px and the other values with px?
Should this also fix the problem with the scrollbar that appears right after the layercontrol is opened? You can see that on the link i posted. Unfortunately im not able implement the fix from where I am, but the problem might be the same.
 


     Davi Custodio <notifications@github.com> schrieb am 19:35 Mittwoch, 24.Juni 2015:
   

 Koni, thank you for taking your webgis so I could play your situation.
I managed to find the problem. When you specify a value for container_maxHeight, type "400px", the plugin in _on_resize_window event had just adding another px value, staying as "400pxpx". It made the StyledLayerControl the container does not resize to the current size of the map.
The Fix is in 9660ef9.
The master is updated too.Thanks—

**Comment by davicustodio** [comment] 2015-06-24 22:56
You do not need to change anything in your code. You can continue using
container_maxHeight: "450px".
The problem was a bug in the code that just correcting.

Thanks

On Wed, Jun 24, 2015 at 3:24 PM, Koni93 <notifications@github.com> wrote:

> Changed/updated everything and worked for me.
> Is it intended to use 'container_maxHeight : "450" ' as a number without
> px and the other values with px?
> Should this also fix the problem with the scrollbar that appears right
> after the layercontrol is opened? You can see that on the link i posted.
> Unfortunately im not able implement the fix from where I am, but the
> problem might be the same.
>
>
>
> Davi Custodio <notifications@github.com> schrieb am 19:35 Mittwoch,
> 24.Juni 2015:
>
>
> Koni, thank you for taking your webgis so I could play your situation.
> I managed to find the problem. When you specify a value for
> container_maxHeight, type "400px", the plugin in _on_resize_window event
> had just adding another px value, staying as "400pxpx". It made the
> StyledLayerControl the container does not resize to the current size of the
> map.
> The Fix is in 9660ef9.
> The master is updated too.Thanks—
>
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davicustodio/Leaflet.StyledLayerControl/issues/7#issuecomment-114971668>
> .
>



-- 
Davi de O. Custódio

**Closed** 2015-06-28 12:10 UTC
